apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "app.fullname" . }}-analysis
spec:
  args:
  - name: service-name
    value: {{ include "app.fullname" . }}
  metrics:
  - name: success-rate
    interval: {{ .Values.analysis.successRate.interval | quote }}
    successCondition: {{ .Values.analysis.successRate.successCondition | quote }}
    failureLimit: {{ .Values.analysis.successRate.failureLimit }}
    count: {{ .Values.analysis.successRate.count }}
    provider:
      prometheus:
        address: http://prometheus.linkerd-viz.svc.cluster.local:9090
        query: |
          (sum(rate(outbound_http_route_backend_response_statuses_total{backend_name="{{ include "app.fullname" . }}-preview", http_status=~"200"}[5m])) / sum(rate(outbound_http_route_backend_response_statuses_total{backend_name="{{ include "app.fullname" . }}-preview"}[5m])) * 100) + ((sum(rate(outbound_http_route_backend_response_statuses_total{backend_name="{{ include "app.fullname" . }}-preview", http_status=~”4..”}[5m])) or sum(rate(outbound_http_route_backend_response_statuses_total{backend_name="{{ include "app.fullname" . }}-preview"}[5m]))) / sum(rate(outbound_http_route_backend_response_statuses_total{backend_name="{{ include "app.fullname" . }}-preview"}[5m])) * 100)