apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "app.fullname" . }}-app-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: {{ include "app.fullname" . }}-server
    kind: Server
    group: policy.linkerd.io
  - name: {{ include "app.fullname" . }}-active
    kind: Service
    group: core
    port: {{ .Values.service.port }}
  rules:
  - matches:
    - path:
        value: "/v1/"
        type: "PathPrefix"
      method: GET
    backendRefs:
    - name: {{ include "app.fullname" . }}-active
      namespace: {{ .Values.namespace }}
      port: {{ .Values.service.port }}
    - name: {{ include "app.fullname" . }}-preview
      namespace: {{ .Values.namespace }}
      port: {{ .Values.service.port }}
