apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ include "app.fullname" . }}-probe-policy
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: {{ include "app.fullname" . }}-probe-route
  requiredAuthenticationRefs:
  - name: {{ include "app.fullname" . }}-probe-authn
    kind: NetworkAuthentication
    group: policy.linkerd.io
