apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
type: Opaque
data:
  addr: {{ .Values.redis.addr | b64enc }}
  password: {{ .Values.redis.password | b64enc }}
  db: {{ .Values.redis.db | toString | b64enc }}