apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "app.fullname" . }}-rollouts-http-route
  namespace: default
spec:
  parentRefs:
  - name: {{ include "app.fullname" . }}-active
    namespace: {{ .Values.namespace }}
    kind: Service
    group: core
    port: {{ .Values.service.port }}
  rules:
  - backendRefs:
    - name: {{ include "app.fullname" . }}-active
      namespace: {{ .Values.namespace }}
      port: {{ .Values.service.port }}
    - name: {{ include "app.fullname" . }}-preview
      namespace: {{ .Values.namespace }}
      port: {{ .Values.service.port }}