apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}-metrics
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 15s