name: Main CI pipeline
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches: [main]
jobs:
  repo-meta:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/gen-repo-meta.yaml@v2

  promote-image:
    needs: [repo-meta]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Fetch Remote Branches
      run: |
        git fetch --all

    - name: Find Commit SHA for Staging
      id: image-sha
      run: |
        MERGING_BRANCH="${{ github.event.pull_request.head.ref }}"
        BASE_COMMIT=$(git merge-base $MERGING_BRANCH develop)
        
        echo "BASE_COMMIT=${BASE_COMMIT}" >> $GITHUB_ENV
        echo $BASE_COMMIT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Promote Image
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.repo-meta.outputs.repository_name }}

        echo "Pulling image: ${IMAGE_NAME}:${BASE_COMMIT}"
        docker pull ${IMAGE_NAME}:${BASE_COMMIT}
        docker tag ${IMAGE_NAME}:${BASE_COMMIT} ${IMAGE_NAME}:latest

        echo "Pushing image: ${IMAGE_NAME}:latest"
        docker push ${IMAGE_NAME}:latest