name: Production CI pipeline
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches: [main]
jobs:
  repo-meta:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/gen-repo-meta.yaml@v2

  retrieve-versions:
    runs-on: ubuntu-latest
    outputs:
      chart_version: ${{ steps.chart-version.outputs.CHART_VERSION }}
      base_commit: ${{ steps.image-sha.outputs.BASE_COMMIT }}
    needs: [repo-meta]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Find Commit SHA for Staging
      id: image-sha
      env:
        MERGING_BRANCH: ${{ github.event.pull_request.head.ref }}
      run: |
        BASE_COMMIT=$(git merge-base "remotes/origin/$MERGING_BRANCH" remotes/origin/develop)

        echo "BASE_COMMIT=${BASE_COMMIT}" >> $GITHUB_OUTPUT
        echo $BASE_COMMIT

    - name: Retrieve chart version
      id: chart-version
      run: |
        CHART_VERSION="$(cat VERSION_HELM)"
        echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_OUTPUT

  promote-artifacts:
    needs: [repo-meta, retrieve-versions]
    uses: hasAnybodySeenHarry/workflows/.github/workflows/promote-artifacts.yaml@main
    with:
      destination: "production"
      base_commit: ${{ needs.retrieve-versions.outputs.base_commit }}
      chart_version: ${{ needs.retrieve-versions.outputs.chart_version }}
      chart_name: ${{ needs.repo-meta.outputs.repository_name }}
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      helm_repo_name: ${{ secrets.HELM_REPO_NAME }}
      helm_repo_owner: ${{ vars.HELM_REPO_OWNER }}
      helm_repo_pat: ${{ secrets.HELM_REPO_PAT }}
