name: Issue Creator
on:
  push:
    branches:
      - "test"
permissions:
  contents: read
  issues: write
jobs:
  issue-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_HASH: ${{ github.sha }}
        with:
          assignees: ${{ github.actor }}
