name: Staging CI pipeline
on:
  push:
    branches: ['release/**']

jobs:
  repo-meta:
    uses: hasAnybodySeenHarry/workflows/.github/workflows/gen-repo-meta.yaml@main

  promote-image:
    needs: [repo-meta]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Find Commit SHA for Staging
      id: image-sha
      run: |
        BASE_COMMIT=$(git rev-parse "${{ github.ref_name }}")
        echo "BASE_COMMIT=${BASE_COMMIT}" >> $GITHUB_ENV
        echo $BASE_COMMIT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Promote Image
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.repo-meta.outputs.repository_name }}

        echo "Pulling image: ${IMAGE_NAME}:${BASE_COMMIT}"
        docker pull ${IMAGE_NAME}:${BASE_COMMIT}
        docker tag ${IMAGE_NAME}:${BASE_COMMIT} ${IMAGE_NAME}:staging

        echo "Pushing image: ${IMAGE_NAME}:staging"
        docker push ${IMAGE_NAME}:staging